# Mapping of ID-based keywords to their URL formats
ID_LINK_MAP = {
    "post": "https://danbooru.donmai.us/posts/",
    "asset": "https://danbooru.donmai.us/media_assets/",
    "topic": "https://danbooru.donmai.us/forum_topics/",
    "forum": "https://danbooru.donmai.us/forum_posts/",
    "comment": "https://danbooru.donmai.us/comments/",
    "pool": "https://danbooru.donmai.us/pools/",
    "favgroup": "https://danbooru.donmai.us/favorite_groups/",
    "wiki": "https://danbooru.donmai.us/wiki_pages/",
    "user": "https://danbooru.donmai.us/users/",
    "ban": "https://danbooru.donmai.us/bans/",
    "feedback": "https://danbooru.donmai.us/user_feedbacks/",
    "appeal": "https://danbooru.donmai.us/post_appeals/",
    "flag": "https://danbooru.donmai.us/post_flags/",
    "note": "https://danbooru.donmai.us/notes/",
    "BUR": "https://danbooru.donmai.us/bulk_update_requests/",
    "alias": "https://danbooru.donmai.us/tag_aliases/",
    "implication": "https://danbooru.donmai.us/tag_implications/",
    "mod action": "https://danbooru.donmai.us/mod_actions/",
    "artist": "https://danbooru.donmai.us/artists/",
    "issue": "https://github.com/danbooru/danbooru/issues/",
    "pixiv": "https://www.pixiv.net/artworks/",
    "pawoo": "https://pawoo.net/web/statuses/",
    "seiga": "https://seiga.nicovideo.jp/seiga/im",
    "nijie": "https://nijie.info/view.php?id=",
    "twitter": "https://twitter.com/i/web/status/",
    "deviantart": "https://www.deviantart.com/deviation/",
    "artstation": "https://www.artstation.com/artwork/",
    "sankaku": "https://chan.sankakucomplex.com/post/show/",
    "gelbooru": "https://gelbooru.com/index.php?page=post&s=view&id=",
    "yandere": "https://yande.re/post/show/",
}
